### Register a user

POST {{host}}/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "user@test.com",
  "name": "user",
  "password": "password123"
}


### Login a user

POST {{host}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "password123"
}

> {%
    client.global.set("token", response.body.token)
%}
